calculator: main.o addition.o division.o print_result.o
				g++ main.o addition.o division.o print_result.o -o calculator

main.o: main.cpp
				g++ -c main.cpp

addition.o: addition.cpp
				g++ -c addition.cpp

print_result.o: print_result.cpp
				g++ -c print_result.cpp